spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: order-service
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 8082