spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: route_product
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: route_admin
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/mall-admin/$\{segment}


  application:
    name: gateway-service

server:
  port: 8085
